FROM ubuntu:20.04

RUN apt update &&\
    apt install -y g++ gcc wget make vim

# cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.20.1/cmake-3.20.1-linux-x86_64.sh 2> /dev/null &&\
    chmod +x cmake-3.20.1-linux-x86_64.sh &&\
    ./cmake-3.20.1-linux-x86_64.sh --skip-license --prefix=/usr/local &&\
    rm cmake-3.20.1-linux-x86_64.sh
